#
# BTstack example 'hid_mouse_demo' for ESP32 port
#
# Generated by /home/chainer/Downloads/btstack/port/esp32
# On Sat Mar 23 22:38:25 2019

PROJECT_NAME := btgamepad

include $(IDF_PATH)/make/project.mk
